/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#1a1c1e",
        "on-background": "#b0b1b8",
        "surface": "#1a1c1e",
        "surface-dim": "#1a1c1e",
        "surface-bright": "#373a3b",
        "surface-tint": "#b7c4ff",
        "surface-variant": "#1e2022",
        "surface-container-lowest": "#141617",
        "surface-container-low": "#1e2022",
        "surface-container": "#222425",
        "surface-container-high": "#282a2b",
        "surface-container-highest": "#323536",
        "on-surface": "#c8c9d0",
        "on-surface-variant": "#9e9fae",
        "inverse-surface": "#e1e3e4",
        "inverse-on-surface": "#2e3132",
        "inverse-primary": "#2151da",
        "outline": "#3a3b44",
        "outline-variant": "#2a2b34",
        "primary": "#b7c4ff",
        "on-primary": "#002682",
        "primary-container": "#1d4ed8",
        "on-primary-container": "#cad3ff",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b7c4ff",
        "on-primary-fixed": "#001551",
        "on-primary-fixed-variant": "#0039b5",
        "secondary": "#c8c6c5",
        "on-secondary": "#313030",
        "secondary-container": "#474746",
        "on-secondary-container": "#b7b5b4",
        "secondary-fixed": "#e5e2e1",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "tertiary": "#ffb59c",
        "on-tertiary": "#5c1900",
        "tertiary-container": "#a73400",
        "on-tertiary-container": "#ffc9b7",
        "tertiary-fixed": "#ffdbcf",
        "tertiary-fixed-dim": "#ffb59c",
        "on-tertiary-fixed": "#390c00",
        "on-tertiary-fixed-variant": "#832700",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        gutter: "16px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      animation: {
        "pulse-red": "pulse-red 2s infinite",
      },
      keyframes: {
        "pulse-red": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
      },
    },
  },
  plugins: [],
}
